services:
    app:
        image: myapp:latest
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
        environment:
          SPRING_DATASOURCE_URL: ${DB_CONNECTION_URL}
          SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
          SPRING_DATASOURCE_USERNAME: ${DB_USER}
        volumes:
          - ./app:/usr/src/app
        networks:
          - microNetwork
        depends_on:
          - mysqlDb

    mysqlDb:
        image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USER}
          MYSQL_DATABASE: microurldb
          MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
          - "3706:3306"
        volumes:
          - db_data:/var/lib/mysql
        networks:
          - microNetwork

networks:
    microNetwork:
        driver: bridge
volumes:
    db_data:
        driver: local
        name: microurlsql_data_volume_data_volume